artifact_location: file:///c:/Users/user/Desktop/YouTube-Sentiment-Insights/notebooks/tracking
  uri/0
creation_time: 1762254409518
experiment_id: '0'
last_update_time: 1762254409518
lifecycle_stage: active
name: Default
