artifact_location: file:///c:/Users/user/Desktop/YouTube-Sentiment-Insights/notebooks/tracking
  uri/446394264747986928
creation_time: 1762254409528
experiment_id: '446394264747986928'
last_update_time: 1762254409528
lifecycle_stage: active
name: Exp 4 - Handling Imbalanced Data
